# Prior to conda-forge, Copyright 2014-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "at-spi2-atk" %}
{% set version = "2.38.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: cfa008a5af822b36ae6287f18182c40c91dd699c55faa38605881ed175ca464f

build:
  number: 2
  skip: True  # [not linux]
  run_exports:
    - {{ pin_subpackage('at-spi2-atk', max_pin='x') }}

requirements:
  build:
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - {{ compiler('c') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('libxi-devel') }}
    - {{ cdt('libxfixes-devel') }}
    - {{ cdt('libxtst-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }}
  host:
    - at-spi2-core
    - atk
    - dbus
    - glib
    - gobject-introspection
  run:
    # this line can be removed when dbus gets exported properly
    - {{ pin_compatible('dbus') }}

test:
  commands:
    - test -f $PREFIX/include/at-spi2-atk/2.0/atk-bridge.h
    - test -f $PREFIX/lib/libatk-bridge-2.0${SHLIB_EXT}

about:
  home: http://www.gtk.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'bridge for AT-SPI and ATK accessibility technologies'
  description: |
    This package includes libatk-bridge, a library that bridges ATK to the new
    D-Bus based AT-SPI, as well as a corresponding module for gtk+ 2.x. Gtk+ 3.x
    now links against libatk-bridge directly rather than requiring it to be loaded
    as a module.

    These libraries depend on the at-spi2-core code that contains the daemon for
    registering applications, D-Bus helper libraries and the AT-SPI D-Bus specifications.
  dev_url: https://gitlab.gnome.org/GNOME/at-spi2-atk

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
